# Generated by Django 4.0.4 on 2022-05-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryKGZ',
            fields=[
                ('title', models.CharField(max_length=300, verbose_name='Название категории')),
                ('slug', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Kyrgyzstan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.categorykgz', verbose_name='Категория')),
            ],
        ),
    ]
