# Generated by Django 4.0.4 on 2022-05-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='min_price',
            field=models.IntegerField(default=1, verbose_name='Минимальная цена'),
            preserve_default=False,
        ),
    ]
