# Generated by Django 4.0.4 on 2022-04-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название достопримичательноти')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200, verbose_name='Область')),
                ('text', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='region')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination', verbose_name='Фото')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.destination', verbose_name='Достопримичательность')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.region', verbose_name='Область'),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('is_banner', models.BooleanField(default=False, verbose_name='На обложку')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog', verbose_name='Блог')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='На главную')),
                ('is_title', models.BooleanField(default=False, verbose_name='На заглавие')),
                ('is_list_item', models.BooleanField(default=False, verbose_name='Элемент списка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='blog.blog', verbose_name='Блог')),
            ],
        ),
    ]
