# Generated by Django 4.0.4 on 2022-04-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_destination_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedestination',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.destination', verbose_name='Достопримичательность'),
        ),
    ]
